Add main to boilerplate to keep cargo happy.
After rebasing against recent master changes, running `cargo test`
elicits the following error:

    ❯ cargo test -- --test-threads=1  --nocapture
       Compiling libm v0.2.8
       Compiling num-traits v0.2.17
       Compiling getrandom v0.2.12
       Compiling strum_macros v0.26.1
       Compiling castaway v0.2.2
       Compiling static_assertions v1.1.0
       Compiling ppv-lite86 v0.2.17
       Compiling itoa v1.0.10
       Compiling ryu v1.0.16
       Compiling rand_core v0.6.4
       Compiling compact_str v0.7.1
       Compiling rand_xorshift v0.3.0
       Compiling rand_chacha v0.3.1
       Compiling rand v0.8.5
       Compiling image v0.24.8
       Compiling chrono v0.4.33
       Compiling rand_distr v0.4.3
       Compiling strum v0.26.1
       Compiling ratatui v0.26.0
       Compiling flexi_logger v0.27.4
       Compiling plotters-bitmap v0.3.3
       Compiling plotters v0.3.5
       Compiling plotters-ratatui-backend v0.1.3
    (/home/ebardie/src/bytecounter/plotters-ratatui-backend)
    error[E0601]: `main` function not found in crate `boilerplate`
      --> plotters-ratatui-backend/examples/boilerplate.rs:54:2
       |
    54 | }
       |  ^ consider adding a `main` function to
    `plotters-ratatui-backend/examples/boilerplate.rs`

    For more information about this error, try `rustc --explain E0601`.
    error: could not compile `plotters-ratatui-backend` (example
    "boilerplate") due to 1 previous error
    warning: build failed, waiting for other jobs to finish...

This commit adds a dummy main to `examples/boilerplate.rs`, which keeps
`cargo` happy.